import Foundation

enum GarageFocusRoomCopy {
    static let focusRoomNavTitle = "Focus Room"
    static let focusRoomHeaderEyebrow = "Active Drill"
    static let focusRoomHeaderDrillPositionFormat = "Drill {current} of {total}"
    static let focusRoomObjectiveLabel = "Aims to train"
    static let focusRoomExecutionCommandLabel = "Command"
    static let focusRoomPassCheckLabel = "Pass if"
    static let focusRoomRepTargetLabel = "Rep Target"
    static let focusRoomDetailRegionLabel = "Drill Detail"
    static let focusRoomDetailSetupLabel = "Setup"
    static let focusRoomDetailCommonMissLabel = "Common Miss"
    static let focusRoomDetailResetCueLabel = "Reset Cue"
    static let focusRoomDetailEquipmentLabel = "Equipment"
    static let focusRoomRailCurrentLabel = "Current"
    static let focusRoomRailUpcomingLabel = "Upcoming"
    static let focusRoomRailCompletedLabel = "Completed"
    static let focusRoomNoteAddCta = "Add Note"
    static let focusRoomNoteEditCta = "Edit Note"
    static let focusRoomBackCta = "Back"
    static let focusRoomMarkCompleteCta = "Next Drill"
    static let focusRoomEnterReviewCta = "Enter Review"
    static let reviewHandoffNavTitle = "Session Review"
    static let reviewHandoffSubtitle = "Add the notes worth carrying forward."
    static let reviewHandoffPendingFormat = "{remaining} drills still need rep review."
    static let reviewHandoffReadyMessage = "Timed review complete. Ready to save."
    static let reviewHandoffAutoRouteMessage = "All drills complete. Entering review."
    static let reviewHandoffBackToFocusCta = "Back to Focus Room"
    static let reviewHandoffSaveCta = "Save Session & Exit"
}
